### ISSUE TITLE
How to skip libopenvas_wmiclient and libopenvas_wincmd depends?

### ISSUE THREAD

**Issue by hjw21century** [greenbone/openvas#374]
As I want to compile without  openvas-smb, is there some way to disable this module when make configurations?

**Comment by jjnicola** [comment]
Unfortunately this is the wrong channel to ask this, because this is not a bug.
The right channel to ask about this is https://community.greenbone.net/c/gse.

You can compile without the openvas-smb module. The code will solve this internally. You will not be able to run authenticated Windows scans.
Regards.
