### ISSUE TITLE
plugin_feed_info.inc not found

### ISSUE THREAD

**Issue by dgiorgio** [greenbone/openvas#508]
### Actual behavior
`openvas: DEBUG: (ospd_openvas.daemon) Plugins feed file /usr/local/var/lib/openvas/plugins/plugin_feed_info.inc not found.`
![image](https://user-images.githubusercontent.com/17960988/82136142-ce6deb00-97e0-11ea-942b-2242cf832d9e.png)

https://github.com/greenbone/openvas/blob/86db3c8e482e4a076bf0c8003d9b9f512ac50bf4/tools/greenbone-nvt-sync.in#L359
https://github.com/greenbone/openvas/blob/86db3c8e482e4a076bf0c8003d9b9f512ac50bf4/tools/greenbone-nvt-sync.in#L421

Solved with
`/usr/bin/rsync -ltvrP --delete --exclude private/ "rsync://feed.community.greenbone.net:/nvt-feed" "/usr/local/var/lib/openvas/plugins"`

### Steps to reproduce

1. Clean installation
2.
3.

### GVM versions

**gsa:** (gsad --version)

**gvm:** (gvmd --version)
Greenbone Vulnerability Manager 9.0.1~git-a5d3e4a1-master
GIT revision a5d3e4a1-master
Manager DB revision 221
Copyright (C) 2010-2017 Greenbone Networks GmbH
License GPLv2+: GNU GPL version 2 or later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**openvas:** (openvas --version)
OpenVAS 7.0.0
gvm-libs 11.0.1
Most new code since 2005: (C) 2019 Greenbone Networks GmbH
Nessus origin: (C) 2004 Renaud Deraison <deraison@nessus.org>
License GPLv2: GNU GPL version 2
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**gvm-libs:**

**openvas-smb:**

**ospd-openvas:** (ospd-openvas --version)
OSP Server for openvas: 1.0.0
OSP: 1.2
OSPd: 2.0.0

Copyright (C) 2014, 2015, 2018, 2019 Greenbone Networks GmbH
License GPLv2+: GNU GPL version 2 or later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

### Environment

**Operating system:**

**Installation method / source:** (packages, source installation)

### Logfiles

```
```

**Comment by cfi-gb** [comment]
Looks like you're looking at the wrong code parts. The plugin_feed_info.inc is excluded here:

https://github.com/greenbone/openvas/blob/86db3c8e482e4a076bf0c8003d9b9f512ac50bf4/tools/greenbone-nvt-sync.in#L359

and synced afterwards a few lines below once the first sync has finished:

https://github.com/greenbone/openvas/blob/86db3c8e482e4a076bf0c8003d9b9f512ac50bf4/tools/greenbone-nvt-sync.in#L364

After the first successful / full sync the plugin_feed_info.inc should be there and DEBUG messages about the missing files looks by design (you can raise your log level to not include DEBUG messages).

I'm closing this as "works by design" for now.
