### ISSUE TITLE
Openvas host/subdomains down for downloading nasl/config files

### ISSUE THREAD

**Issue by Anon-Exploiter** [greenbone/openvas#605]
### Expected behavior

While executing `greenbone-nvt-sync`, `greenbone-scapdata-sync` and `greenbone-certdata-sync`, the backend subdomain/host hosting the files seems down. I've tried accessing the host through both AWS and locally but it's down and isn't working. Not sure, if that's intended (in case it isn't, creating the bug report)

Some helping screenshots:

![image](https://user-images.githubusercontent.com/18597330/95304116-935a7a00-089d-11eb-894a-df6a361d3661.png)

![image](https://user-images.githubusercontent.com/18597330/95304128-96556a80-089d-11eb-969a-bf37a6ec4bd1.png)

![image](https://user-images.githubusercontent.com/18597330/95304136-98b7c480-089d-11eb-9be9-a8b28a71e4bc.png)

**Comment by Anon-Exploiter** [comment]
Okay, so it seems, it works fine for OpenVAS installed on ubuntu 20.04 from (https://launchpad.net/~mrazavi/+archive/ubuntu/gvm). 

The installation on Ubuntu 18.04 LTS gives error. Strange, packages are different on both distros, I guess. 

On 18.04 LTS: 

![image](https://user-images.githubusercontent.com/18597330/95307016-90618880-08a1-11eb-8e8b-595b809a32e9.png)

---

On 20.04 LTS:

![image](https://user-images.githubusercontent.com/18597330/95307045-98212d00-08a1-11eb-82cb-126d098756e1.png)

**Comment by cfi-gb** [comment]
This is expected, the HTTP downloads and the legacy feed.openvas.org are both deprecated and doesn't work anymore as announced in the following community portal postings:

https://community.greenbone.net/t/shutting-down-gcf-http-download/5339
https://community.greenbone.net/t/community-feed-url-consolidation/5338

Newer GVM releases are already ready for these changes, that's why you're seeing these differences.
